import { ArrowRight, Check, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppLink } from "@/components/app-link";
import { ApplyForm } from "@/components/apply-form";
import { ContactForm } from "@/components/contact-form";
import { CourseGrid } from "@/components/course-grid";
import { TiltCard } from "@/components/tilt-card";
import { SectionReveal } from "@/components/section-reveal";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { images, type pageDetails } from "@/lib/site-data";
import directorPhoto from "@/assets/Anees.jfif?url";

type Detail = (typeof pageDetails)[string];
export function ContentPage({ detail, kind, itemTitle }: { detail: Detail; kind: string; itemTitle?: string | undefined }) {
  const title = itemTitle ?? detail.title;
  const isFaculty = kind === "faculty", isResources = kind === "resources", isUpdates = ["news", "events", "blog"].includes(kind), isApply = kind === "admissions" && itemTitle === "Apply";
  return <>
    <section className="relative min-h-[72svh] overflow-hidden bg-primary text-primary-foreground"><img src={detail.image} alt="" width={1536} height={1024} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,oklch(0.23_0.07_287/.84),oklch(0.23_0.07_287/.24)_75%)]"/><div className="relative mx-auto flex min-h-[72svh] max-w-7xl items-end px-6 pb-20 pt-32"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-gold">{detail.kicker}</p><h1 className="mt-5 text-5xl font-extrabold leading-tight md:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/85">{detail.description}</p></div></div></section>
    {isApply ? <ApplyForm/> : kind === "contact" ? <ContactForm/> : isFaculty ? <FacultyContent/> : isResources ? <ResourcesContent/> : isUpdates ? <UpdatesContent kind={kind}/> : <>{kind === "about" && <DirectorMessage/>}{!itemTitle && (kind === "programs" || kind === "academics") && <CourseGrid/>}<StandardContent kind={kind} itemTitle={itemTitle}/></>} 
  </>;
}

function DirectorMessage() {
  return <section className="border-y border-border bg-brand-soft py-20 md:py-28"><div className="mx-auto grid max-w-7xl items-center gap-10 px-6 md:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] md:gap-16"><div className="mx-auto w-full max-w-sm"><img src={directorPhoto} alt="Anees, Director of Unique EdTech" width={768} height={960} loading="lazy" className="aspect-[4/5] w-full rounded-xl object-cover object-top shadow-lg"/></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-red">Leadership</p><h2 className="mt-4 text-4xl font-extrabold md:text-5xl">A message from our Director</h2><blockquote className="mt-6 space-y-4 text-base leading-8 text-muted-foreground md:text-lg"><p>Every child has the potential to ask bold questions, discover new strengths and shape a better future. Our responsibility is to nurture that potential with care, high expectations and learning connected to life.</p><p>At Unique EdTech, we bring strong academic foundations together with technology, creativity and character. We want every student to leave our classrooms curious, confident and ready to contribute with purpose.</p><p>Thank you for trusting us with your child's learning journey.</p></blockquote><div className="mt-8 border-l-2 border-brand-red pl-4"><p className="font-bold text-foreground">Anees</p><p className="mt-1 text-sm text-muted-foreground">Director, Unique EdTech · DM Chapter G, Magnolia</p></div></div></div></section>;
}

function StandardContent({ kind, itemTitle }: { kind:string; itemTitle?:string | undefined }) {
 const sectionTitles = itemTitle ? ["Learning objectives","Curriculum overview","Learning activities","Technology integration","Skills development","Student experience"] : kind === "about" ? ["Our Story","Our Vision","Our Mission","Our Philosophy","Learning Approach","Student Development"] : kind === "admissions" ? ["01 Explore","02 Apply","03 Visit","04 Assessment","05 Enrollment"] : ["Purposeful learning","Designed for participation","Progress with confidence","Connected experiences"];
 return <><section className="py-24"><div className="mx-auto max-w-7xl px-6"><SectionReveal><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-red">The experience</p><h2 className="mt-4 max-w-3xl text-4xl font-extrabold md:text-6xl">A thoughtful environment for meaningful growth.</h2></SectionReveal><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{sectionTitles.map((title,i)=><SectionReveal key={title}><TiltCard className="min-h-56 rounded-2xl border border-border bg-background p-7"><span className="text-sm font-bold text-brand-gold">{String(i+1).padStart(2,"0")}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Students build understanding through clear instruction, guided practice, active inquiry and purposeful reflection.</p></TiltCard></SectionReveal>)}</div></div></section><section className="bg-brand-soft py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2"><img src={kind.includes("program") ? images.coding : images.classroom} alt="Learning in action" width={1536} height={1024} loading="lazy" className="aspect-[4/3] w-full rounded-2xl object-cover"/><div className="self-center"><h2 className="text-4xl font-extrabold">Learning that connects.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">The classroom experience brings together subject knowledge, creativity, communication and responsible technology use.</p><ul className="mt-7 space-y-4">{["Clear learning intentions","Active student participation","Feedback that supports progress","Age-appropriate digital tools"].map(x=><li key={x} className="flex gap-3"><Check className="text-brand-red"/>{x}</li>)}</ul></div></div></section>{itemTitle && <section className="py-24"><div className="mx-auto max-w-3xl px-6"><h2 className="text-4xl font-extrabold">Frequently asked questions</h2><Accordion type="single" collapsible className="mt-8">{["How is learning assessed?","How is technology used?","How can families support learning?"].map((q,i)=><AccordionItem key={q} value={`q-${i}`}><AccordionTrigger className="text-left text-base">{q}</AccordionTrigger><AccordionContent className="leading-6 text-muted-foreground">Detailed guidance is shared with families by the school. Contact the chapter for current, level-specific information.</AccordionContent></AccordionItem>)}</Accordion><Button asChild variant="premium" size="xl" className="mt-10"><AppLink href="/admissions/apply">Apply now <ArrowRight/></AppLink></Button></div></section>}</>;
}

function FacultyContent(){return <section className="py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 lg:grid-cols-2"><img src={images.mentoring} alt="Teacher supporting students as they learn" width={1536} height={1024} loading="lazy" className="aspect-[4/3] w-full rounded-xl object-cover"/><div><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-red">Our educators</p><h2 className="mt-4 text-4xl font-extrabold">Guidance shaped around every learner.</h2><p className="mt-5 leading-7 text-muted-foreground">Our educators help students build strong foundations, explore ideas with confidence and connect learning to the world around them.</p><ul className="mt-7 space-y-4">{["Clear instruction and guided practice","Curiosity, creativity and purposeful technology","Respectful communication with students and families"].map(item=><li key={item} className="flex gap-3"><Check className="shrink-0 text-brand-red"/>{item}</li>)}</ul><p className="mt-7 text-sm text-muted-foreground">For current staff names, roles and subject information, please contact the school.</p><Button asChild variant="premium" size="xl" className="mt-6"><AppLink href="/contact">Contact the school <ArrowRight/></AppLink></Button></div></div></section>}
function ResourcesContent(){return <section className="py-24"><div className="mx-auto max-w-7xl px-6"><SectionReveal><h2 className="text-4xl font-extrabold">Family & student resources.</h2><p className="mt-4 max-w-2xl text-muted-foreground">Request the latest school documents from the office. The school can confirm current versions and availability.</p></SectionReveal><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{["Academic Calendar","School Policies","Admission Information","Downloads","Parent Resources","Student Resources","Forms"].map(item=><TiltCard key={item} className="rounded-xl border border-border bg-background p-6"><h3 className="text-lg font-bold">{item}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Email the school office to request this resource.</p><Button asChild variant="premiumOutline" className="mt-8"><a href={`mailto:uniquedmchapter@gmail.com?subject=${encodeURIComponent(`Request: ${item}`)}`}><Mail/>Request by email</a></Button></TiltCard>)}</div></div></section>}
function UpdatesContent({ kind }: { kind: string }){const category=kind === "events" ? "Events" : kind === "blog" ? "Journal" : "News"; return <section className="py-24"><div className="mx-auto max-w-3xl px-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-red">{category}</p><h2 className="mt-4 text-4xl font-extrabold">Updates will appear here when confirmed.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">For current {category.toLowerCase()} information, contact the school office directly.</p><Button asChild variant="premium" size="xl" className="mt-8"><AppLink href="/contact">Contact the school <ArrowRight/></AppLink></Button></div></section>}