import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Code2, Cpu, Lightbulb, Microscope, Palette, ShieldCheck, Sparkles, X } from "lucide-react";
import { AppLink } from "@/components/app-link";
import { Button } from "@/components/ui/button";
import { ParallaxImage } from "@/components/parallax-image";
import { SectionReveal } from "@/components/section-reveal";
import { TiltCard } from "@/components/tilt-card";
import { images } from "@/lib/site-data";
import { LocationSection, ParentPartnershipSection, YouTubeSection } from "@/components/home-extra-sections";

const courses = [
  ["Early Years", "Play Group", "Playful discovery, language and social confidence.", "Foundation stage", images.creative, "/academics/play-group"],
  ["Early Years", "Nursery", "Early literacy, numeracy and curious exploration.", "Early years", images.classroom, "/academics/nursery"],
  ["Early Years", "Prep", "Confident foundations for the primary journey.", "School readiness", images.library, "/academics/prep"],
  ...Array.from({ length: 9 }, (_, i) => {
    const grade = i + 1;
    const category = grade <= 5 ? "Primary" : grade <= 7 ? "Middle School" : "Secondary";
    const focus = grade <= 5 ? "Core foundations" : grade <= 7 ? "Independent inquiry" : "Secondary readiness";
    const photos = [images.classroom, images.library, images.mentoring];
    return [category, `Grade ${grade}`, "Knowledge, skills and confidence developed through active learning.", focus, photos[i % photos.length] ?? images.classroom, `/academics/grade-${grade}`];
  }),
  ["Technology", "Information Technology", "Practical digital fluency for purposeful learning.", "Digital systems", images.coding, "/programs/information-technology"],
  ["Technology", "Computer Science", "Computational thinking and structured problem-solving.", "Computing", images.coding, "/programs/computer-science"],
  ["Technology", "Coding", "Create, test and improve ideas through code.", "Creative computing", images.coding, "/programs/coding"],
  ["Technology", "Robotics", "Design and build responsive working systems.", "Engineering", images.robotics, "/programs/robotics"],
  ["Technology", "Artificial Intelligence", "Age-appropriate foundations for responsible AI learning.", "Emerging technology", images.classroom, "/programs/artificial-intelligence"],
  ["Technology", "STEM", "Connect science, technology, engineering and mathematics.", "Applied inquiry", images.robotics, "/programs/stem"],
  ["Technology", "Digital Skills", "Confident, safe and responsible participation online.", "Digital literacy", images.coding, "/programs/digital-literacy"],
] as const;

const categories = ["All", "Early Years", "Primary", "Middle School", "Secondary", "Technology"] as const;
const activityItems = [
  ["Sports", images.sports], ["Debate", images.library], ["Public Speaking", images.mentoring], ["Science Fair", images.robotics], ["Robotics", images.robotics], ["Coding", images.coding], ["Arts", images.creative], ["Competitions", images.classroom], ["Field Trips", images.campus], ["Events", images.sports],
] as const;

function RailControls({ rail, label }: { rail: React.RefObject<HTMLDivElement | null>; label: string }) {
  const move = (direction: number) => rail.current?.scrollBy({ left: direction * Math.min(430, window.innerWidth * .8), behavior: "smooth" });
  return <div className="flex gap-2"><Button variant="premiumOutline" size="icon" aria-label={`Previous ${label}`} onClick={() => move(-1)}><ArrowLeft /></Button><Button variant="premiumOutline" size="icon" aria-label={`Next ${label}`} onClick={() => move(1)}><ArrowRight /></Button></div>;
}

function LearningJourney() {
  const [filter, setFilter] = useState<(typeof categories)[number]>("All");
  const rail = useRef<HTMLDivElement>(null);
  const visible = courses.filter(([category]) => filter === "All" || category === filter);
  return <section id="academics" className="fog-section overflow-hidden bg-brand-soft py-24 md:py-32"><div className="mx-auto max-w-7xl px-6"><SectionReveal><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow">Academic journey</p><h2 className="section-title">Explore Our Learning Journey</h2><p className="section-copy">From early learning to future-ready skills, every stage is designed to help students learn, create and grow with confidence.</p></div><div className="shrink-0"><RailControls rail={rail} label="courses" /></div></div></SectionReveal><div className="mt-10 flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="Course categories">{categories.map((category) => <Button key={category} role="tab" aria-selected={filter === category} variant={filter === category ? "premium" : "premiumOutline"} size="sm" onClick={() => setFilter(category)} className="shrink-0">{category}</Button>)}</div></div><div ref={rail} className="scrollbar-hidden mt-8 flex snap-x snap-mandatory gap-5 overflow-x-auto px-[max(1.5rem,calc((100vw-80rem)/2))] pb-10">{visible.map(([category, title, text, focus, image, href], i) => <SectionReveal key={href} delay={(i % 4) * 90} className="min-w-[84vw] snap-start sm:min-w-[46vw] lg:min-w-[calc((80rem-3.75rem)/4)] lg:max-w-[305px]"><AppLink href={href} className="block h-full"><TiltCard className="h-full overflow-hidden rounded-2xl border border-border bg-background"><div className="card-media aspect-[4/3] overflow-hidden"><img src={image} alt={`${title} learning`} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover" /></div><div className="relative z-10 p-6"><p className="text-xs font-bold uppercase text-brand-red">{category}</p><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{text}</p><div className="mt-5 border-t border-border pt-4"><span className="text-xs text-muted-foreground">Learning focus</span><p className="mt-1 text-sm font-semibold">{focus}</p></div><span className="card-cta mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Explore course <ArrowRight className="size-4" /></span></div></TiltCard></AppLink></SectionReveal>)}</div><div className="mx-auto max-w-7xl px-6"><Button asChild variant="premiumOutline" size="xl"><AppLink href="/academics">View all courses <ArrowRight /></AppLink></Button></div></section>;
}

function CampusGallery() {
  const [selected, setSelected] = useState<number | null>(null);
  const gallery = [[images.campus,"Campus"],[images.classroom,"Classrooms"],[images.library,"Library"],[images.coding,"Computer Lab"],[images.robotics,"Science & Robotics Lab"],[images.sports,"Sports"],[images.creative,"Activities"],[images.mentoring,"Student Areas"]] as const;
  useEffect(() => {
    if (selected === null) return;
    const key = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); if (event.key === "ArrowRight") setSelected((selected + 1) % gallery.length); if (event.key === "ArrowLeft") setSelected((selected - 1 + gallery.length) % gallery.length); };
    window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key);
  }, [selected, gallery.length]);
  return <section id="campus" className="fog-section py-24 md:py-32"><div className="mx-auto max-w-7xl px-6"><SectionReveal><p className="eyebrow">Campus life</p><h2 className="section-title">Spaces that invite possibility.</h2><p className="section-copy">Learning moves between focused classrooms, collaborative spaces, technology areas and places to create, move and connect.</p></SectionReveal><div className="mt-12 grid auto-rows-[210px] grid-cols-2 gap-4 md:auto-rows-[260px] md:grid-cols-4">{gallery.map(([image,label],i)=><SectionReveal key={label} delay={(i%4)*90} className={i===0 || i===5 ? "col-span-2 row-span-2" : ""}><TiltCard className="gallery-card h-full overflow-hidden rounded-2xl"><button type="button" onClick={()=>setSelected(i)} aria-label={`View ${label} image`} className="group relative h-full w-full overflow-hidden text-left"><img src={image} alt={label} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute inset-0 bg-linear-to-t from-primary/75 via-transparent to-transparent"/><span className="absolute bottom-0 left-0 right-0 flex items-center justify-between p-5 font-bold text-primary-foreground"><span>{label}</span><span className="translate-y-2 opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100">View</span></span></button></TiltCard></SectionReveal>)}</div></div>{selected !== null && <div role="dialog" aria-modal="true" aria-label={`${gallery[selected]?.[1]} image`} className="fixed inset-0 z-[80] grid place-items-center bg-primary/95 p-4" onClick={()=>setSelected(null)}><Button size="icon" variant="heroOutline" aria-label="Close image" className="absolute right-5 top-5" onClick={()=>setSelected(null)}><X/></Button><Button size="icon" variant="heroOutline" aria-label="Previous image" className="absolute left-5" onClick={(e)=>{e.stopPropagation();setSelected((selected-1+gallery.length)%gallery.length)}}><ArrowLeft/></Button><img src={gallery[selected]?.[0]} alt={gallery[selected]?.[1]} className="max-h-[82vh] max-w-[88vw] rounded-2xl object-contain" onClick={(e)=>e.stopPropagation()}/><Button size="icon" variant="heroOutline" aria-label="Next image" className="absolute right-5" onClick={(e)=>{e.stopPropagation();setSelected((selected+1)%gallery.length)}}><ArrowRight/></Button></div>}</section>;
}

function Activities() {
  const rail = useRef<HTMLDivElement>(null);
  return <section id="activities" className="fog-section overflow-hidden bg-brand-soft py-24"><div className="mx-auto flex max-w-7xl items-end justify-between gap-6 px-6"><SectionReveal><p className="eyebrow">Beyond lessons</p><h2 className="section-title">A fuller school experience.</h2></SectionReveal><RailControls rail={rail} label="activities"/></div><div ref={rail} className="scrollbar-hidden mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto px-[max(1.5rem,calc((100vw-80rem)/2))] pb-6">{activityItems.map(([title,img],i)=><SectionReveal key={title} delay={(i%4)*80} className="min-w-[78vw] snap-start sm:min-w-[360px]"><AppLink href="/activities"><TiltCard className="overflow-hidden rounded-2xl border border-border bg-background"><div className="card-media aspect-[4/3] overflow-hidden"><img src={img} alt={title} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover"/></div><div className="relative z-10 flex items-center justify-between p-6"><h3 className="text-lg font-bold">{title}</h3><ArrowRight className="card-arrow size-5"/></div></TiltCard></AppLink></SectionReveal>)}</div></section>;
}

export function HomepageSections() {
  const values = [[Microscope,"Academic Excellence","Strong foundations, active inquiry and confident progress."],[Cpu,"Technology-Enabled Learning","Digital tools used thoughtfully to deepen understanding."],[Lightbulb,"STEM & Innovation","Hands-on investigation that turns curiosity into ideas."],[Palette,"Creative Development","Space to imagine, design and express original thinking."],[Sparkles,"Confidence & Communication","Learners find their voice through purposeful participation."],[ShieldCheck,"Safe Learning Environment","A respectful culture where every learner can belong."]] as const;
  const steps = ["Discover","Learn","Create","Collaborate","Lead"];
  const exploreItems = [[images.campus,"Campus life","Explore spaces for focused learning, practical discovery and collaboration.","Explore campus","/campus-life"],[images.robotics,"Programs","Discover coding, robotics, digital literacy and hands-on STEM.","Explore programs","/programs"],[images.creative,"Activities","Find sport, creative work and experiences beyond lessons.","Explore activities","/activities"]] as const;
  return <>
    <section className="fog-section overflow-hidden py-24 md:py-36"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-[1.1fr_.9fr]"><SectionReveal direction="scale" className="relative"><div className="overflow-hidden rounded-2xl"><ParallaxImage src={images.mentoring} alt="Teacher supporting students beyond the classroom" className="aspect-[4/3] w-full object-cover"/></div><div className="absolute -bottom-8 right-4 max-w-xs rounded-2xl border border-border bg-background p-5 shadow-xl md:right-[-2rem]"><p className="text-sm font-bold">Learning with purpose</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Knowledge, creativity and character grow together.</p></div></SectionReveal><SectionReveal direction="left"><p className="eyebrow">Welcome to Unique EdTech</p><h2 className="section-title">Learning Beyond the Classroom</h2><p className="section-copy">A modern educational environment where strong academics meet technology, creativity and personal growth.</p><div className="mt-8 space-y-5">{["Academic Excellence","Future-Ready Learning","Student Development"].map((x,i)=><div key={x} className="flex items-center gap-4 border-b border-border pb-5"><span className="text-sm font-bold text-brand-gold">0{i+1}</span><span className="font-semibold">{x}</span></div>)}</div></SectionReveal></div></section>
    <section className="fog-section bg-background py-24 md:py-32"><div className="mx-auto max-w-7xl px-6"><SectionReveal><p className="eyebrow">Why Unique EdTech</p><h2 className="section-title">An education designed for what comes next.</h2></SectionReveal><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{values.map(([Icon,title,text],i)=><SectionReveal key={title} delay={(i%3)*100}><TiltCard className="min-h-64 rounded-2xl border border-border bg-background p-7"><div className="card-icon mb-12 grid size-12 place-items-center rounded-xl bg-primary text-primary-foreground"><Icon/></div><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></TiltCard></SectionReveal>)}</div></div></section>
    <LearningJourney/>
    <section id="programs" className="fog-section relative min-h-[760px] overflow-hidden bg-primary"><ParallaxImage src={images.coding} alt="Students preparing for the digital future" className="absolute inset-[-5%] h-[110%] w-[110%] object-cover opacity-80"/><div className="absolute inset-0 bg-linear-to-r from-transparent via-primary/35 to-primary/95"/><div className="relative mx-auto flex min-h-[760px] max-w-7xl items-center justify-end px-6"><SectionReveal direction="left" className="w-full max-w-xl text-primary-foreground"><p className="eyebrow text-brand-gold">Technology & EdTech</p><h2 className="mt-4 text-4xl font-extrabold md:text-6xl">Preparing Students for the Digital Future</h2><p className="mt-6 text-lg leading-8 text-primary-foreground/80">Technology supports active learning, responsible participation and confident creation—not passive screen time.</p><div className="mt-8 flex flex-wrap gap-3">{["Coding","Digital Literacy","Robotics","AI","Computer Science"].map((x,i)=><span key={x} className="floating-chip" style={{transform:`translateY(${i%2?8:0}px)`}}>{x}</span>)}</div><Button asChild variant="hero" size="xl" className="mt-10"><AppLink href="/programs">Explore programs <ArrowRight/></AppLink></Button></SectionReveal></div></section>
    <section className="fog-section py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-2 lg:items-center"><SectionReveal direction="right"><div className="overflow-hidden rounded-2xl"><ParallaxImage src={images.robotics} alt="Students imagining, building and innovating with robotics" className="aspect-[4/3] w-full object-cover"/></div></SectionReveal><SectionReveal direction="left"><p className="eyebrow">STEM + Robotics</p><h2 className="section-title">Imagine. Build. Innovate.</h2><p className="section-copy">Students connect science, technology, engineering, mathematics and coding through practical challenges, prototypes and reflection.</p><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3">{["Robotics","Engineering","Science","Coding","Experiments","STEM"].map(x=><div key={x} className="border-l-2 border-brand-gold py-2 pl-4 text-sm font-bold">{x}</div>)}</div><Button asChild variant="premium" size="xl" className="mt-10"><AppLink href="/programs/stem">Explore STEM <ArrowRight/></AppLink></Button></SectionReveal></div></section>
    <section className="fog-section bg-primary py-24 text-primary-foreground md:py-32"><div className="mx-auto max-w-7xl px-6"><SectionReveal><p className="eyebrow text-brand-gold">Learning experience</p><h2 className="section-title">How We Help Students Grow</h2></SectionReveal><div className="relative mt-14 grid gap-3 md:grid-cols-5"><div className="absolute left-0 right-0 top-7 hidden h-px bg-primary-foreground/20 md:block"/>{steps.map((step,i)=><SectionReveal key={step} delay={i*100}><div className="group relative"><span className="relative z-10 grid size-14 place-items-center rounded-full border border-primary-foreground/30 bg-primary text-sm font-bold transition-colors group-hover:bg-brand-red">0{i+1}</span><h3 className="mt-7 text-xl font-bold">{step}</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/65">Each stage builds knowledge, agency and confidence for the next.</p></div></SectionReveal>)}</div></div></section>
    <CampusGallery/>
    <Activities/>
    <YouTubeSection/>
    <ParentPartnershipSection/>
    <section className="fog-section py-24 md:py-32"><div className="mx-auto max-w-7xl px-6"><SectionReveal><p className="eyebrow">Explore Unique EdTech</p><h2 className="section-title">Discover learning across our school.</h2></SectionReveal><div className="mt-12 grid gap-5 md:grid-cols-3">{exploreItems.map(([image,category,text,link,href],i)=><SectionReveal key={category} delay={i*100}><AppLink href={href}><TiltCard className="h-full overflow-hidden rounded-2xl border border-border bg-background"><div className="card-media aspect-[16/10] overflow-hidden"><img src={image} alt={category} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover"/></div><div className="relative z-10 p-6"><p className="text-xs font-bold uppercase text-brand-red">{category}</p><p className="mt-4 text-sm leading-6 text-muted-foreground">{text}</p><span className="card-cta mt-6 inline-flex items-center gap-2 text-sm font-bold">{link} <ArrowRight className="size-4"/></span></div></TiltCard></AppLink></SectionReveal>)}</div></div></section>
    <LocationSection/>
    <section id="admissions" className="relative min-h-[620px] overflow-hidden text-primary-foreground"><ParallaxImage src={images.campus} alt="Unique EdTech campus and students" className="absolute inset-[-5%] h-[110%] w-[110%] object-cover"/><div className="absolute inset-0 bg-primary/70"/><div className="relative mx-auto flex min-h-[620px] max-w-7xl items-center px-6"><SectionReveal className="max-w-3xl"><p className="eyebrow text-brand-gold">Admissions</p><h2 className="mt-4 text-4xl font-extrabold md:text-7xl">Start Your Child's Journey With Us</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/80">Explore a learning environment shaped by academic purpose, technology, creativity and care.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild variant="hero" size="xl"><AppLink href="/admissions/apply">Apply now <ArrowRight/></AppLink></Button><Button asChild variant="heroOutline" size="xl"><AppLink href="/contact">Contact us <ArrowRight/></AppLink></Button></div></SectionReveal></div></section>
  </>;
}